#!/usr/bin/env bash

dir=$1
if [[ -z "$dir" ]]; then
	echo "error: please provide a directory to convert"
	exit 1
fi

out_dir="${dir}-720p"

for f in $(find $dir -type f); do
	fname=$(basename $f)
	dname="${f#$dir}"
	dname="$(dirname $dname)"
	prefix="/"
	dname="${dname#$prefix}"
	out="${out_dir}/${dname}/${fname}"

	if [ -f "$out" ]; then
		# NOTE: file already exists, skip it
		continue
	fi

	mkdir -p "${out_dir}/${dname}"

	ffmpeg -i "$f" -vf scale=-1:720 -c:v libx264 -crf 18 -preset veryslow -c:a copy "$out" 
	if [ $? != 0 ]; then
		rm -fr $out
		mkdir -p "${out_dir}/${dname}"
		cp "$f" "$out" # NOTE: generally, videos should play well. Copy the un-transformed file in-lieue of actually transforming it if it fails
	fi
	
done 
